version: '3.8'
name: cronjobexample
services:
  app:
    build:
      context: /
      dockerfile: Dockerfile
    ports:
      - 9000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: app